<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="HttpException.xml" source-language="en-US" target-language="ru-RU">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-15c36f0" tool-company="Microsoft" />
      <xliffext:skl_file_name xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02cd5861-7ce2-4a82-b358-31f8435a0ac51864e8fe52f0eb87b7c23fbfe505d15cf9681ede.skl</xliffext:skl_file_name>
      <xliffext:version xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1.2</xliffext:version>
      <xliffext:ms.openlocfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1864e8fe52f0eb87b7c23fbfe505d15cf9681ede</xliffext:ms.openlocfilehash>
      <xliffext:ms.sourcegitcommit xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b</xliffext:ms.sourcegitcommit>
      <xliffext:ms.lasthandoff xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">04/03/2018</xliffext:ms.lasthandoff>
      <xliffext:moniker_ids xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">netframework-4.5.1,netframework-4.5.2,netframework-4.5,netframework-4.6.1,netframework-4.6.2,netframework-4.6,netframework-4.7.1,netframework-4.7</xliffext:moniker_ids>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" uid="T:System.Web.HttpException">
          <source>Describes an exception that occurred during the processing of HTTP requests.</source>
          <target state="translated">Описывает исключение, которое возникает при обработке HTTP-запросов.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.HttpException">
          <source>The <ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> class is an HTTP-specific exception class that enables ASP.NET to generate exception information.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> Класс является классом исключений HTTP-протокол, позволяющий ASP.NET для создания информации об исключении.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.HttpException">
          <source>For more information about throwing and handling exceptions, see <bpt id="p1">[</bpt>Exceptions<ept id="p1">](http://msdn.microsoft.com/library/f99a1d29-a2a8-47af-9707-9909f9010735)</ept>.</source>
          <target state="translated">Дополнительные сведения о генерации и обработке исключений см. в разделе <bpt id="p1">[</bpt>исключения<ept id="p1">](http://msdn.microsoft.com/library/f99a1d29-a2a8-47af-9707-9909f9010735)</ept>.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.HttpException">
          <source>The following code example demonstrates how to use the <ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> class to raise customized exceptions.</source>
          <target state="translated">В следующем примере кода демонстрируется использование <ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> класса для формирования настраиваемых исключений.</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.HttpException">
          <source>The <ph id="ph1">`Button_Click`</ph> method determines which button was clicked, and then calls either the <ph id="ph2">`CheckNumber`</ph> or <ph id="ph3">`CheckBoolean`</ph> method.</source>
          <target state="translated"><ph id="ph1">`Button_Click`</ph> Метод определяет, какая кнопка была нажата и затем вызывает метод <ph id="ph2">`CheckNumber`</ph> или <ph id="ph3">`CheckBoolean`</ph> метод.</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.HttpException">
          <source>If the user-entered value in the text box does not correspond to the expected type, an <ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> exception is created and thrown with a customized message based on the error type.</source>
          <target state="translated">Если введенное пользователем значение в текстовом поле не соответствует ожидаемому типу <ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> создается исключение и вызывается с настраиваемым сообщением, в зависимости от типа ошибки.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.HttpException">
          <source>This example has a text box that accepts user input, which is a potential security threat.</source>
          <target state="translated">В этом примере имеется текстовое поле, принимающее вводимые пользователем данные, что является потенциальной угрозой безопасности.</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.HttpException">
          <source>By default, ASP.NET Web pages validate that user input does not include script or HTML elements.</source>
          <target state="translated">По умолчанию данные, вводимые пользователем на веб-страницах ASP.NET, проверяются на наличие скриптов и HTML-элементов.</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.HttpException">
          <source>For more information, see <bpt id="p1">[</bpt>Script Exploits Overview<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>.</source>
          <target state="translated">Дополнительные сведения см. в разделе <bpt id="p1">[</bpt>Общие сведения об использовании сценариев<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>.</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" uid="T:System.Web.HttpException">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> class.</source>
          <target state="translated">Инициализирует новый экземпляр класса <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> class and creates an empty <ph id="ph2">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> object.</source>
          <target state="translated">Выполняет инициализацию нового экземпляра класса <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> и создает пустой объект <ph id="ph2">&lt;see cref="T:System.Web.HttpException" /&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor">
          <source>When handling exceptions, it can be useful to capture a series of related exceptions with the outer exception being thrown in response to an inner exception.</source>
          <target state="translated">При обработке исключений, его можно использовать для захвата ряд исключений, связанных с внешней исключения в ответ на внутреннее исключение.</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor">
          <source>A reference to the inner exception that caused the outer exception is available from the <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property of the outer exception.</source>
          <target state="translated">Ссылка на внутреннее исключение, вызвавшее исключение внешнего доступна через <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> свойства внешнего исключения.</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor">
          <source>This mechanism preserves the error information that is carried by earlier exceptions, including the original exceptions, while allowing you to create more meaningful outer exceptions.</source>
          <target state="translated">Этот механизм сохраняет сведения об ошибке, переданные в более ранних исключениях, включая исходные исключения, предоставляя возможность создания более значимых внешних исключений.</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor">
          <source>For more information, see <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph>.</source>
          <target state="translated">Дополнительные сведения см. в разделе <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor">
          <source>The following code example demonstrates the <ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph> constructor of the <ph id="ph2">&lt;xref:System.Web.HttpException&gt;</ph> class.</source>
          <target state="translated">В следующем примере кода показано <ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph> конструктор <ph id="ph2">&lt;xref:System.Web.HttpException&gt;</ph> класса.</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor">
          <source>The <ph id="ph1">`CheckNumber`</ph> method accepts a user-entered value through a text box and checks whether it is an integer.</source>
          <target state="translated"><ph id="ph1">`CheckNumber`</ph> Метод введенное пользователем значение в текстовое поле и проверяет, является ли это целое число.</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor">
          <source>If the value is not an integer, an exception is thrown, and then a new <ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> object is created and thrown.</source>
          <target state="translated">Если значение не является целым числом, создается исключение и создается новый <ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> объект создается и исключение.</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor">
          <source>That exception is caught in the <ph id="ph1">`Button_Click`</ph> event handler and the error message is displayed on the browser.</source>
          <target state="translated">Что исключение перехватывается в <ph id="ph1">`Button_Click`</ph> обработчик событий и сообщение об ошибке отображается в браузере.</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor">
          <source>This example has a text box that accepts user input, which is a potential security threat.</source>
          <target state="translated">В этом примере имеется текстовое поле, принимающее вводимые пользователем данные, что является потенциальной угрозой безопасности.</target>       </trans-unit>
        <trans-unit id="121" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor">
          <source>By default, ASP.NET Web pages validate that user input does not include script or HTML elements.</source>
          <target state="translated">По умолчанию данные, вводимые пользователем на веб-страницах ASP.NET, проверяются на наличие скриптов и HTML-элементов.</target>       </trans-unit>
        <trans-unit id="122" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor">
          <source>For more information, see <bpt id="p1">[</bpt>Script Exploits Overview<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>.</source>
          <target state="translated">Дополнительные сведения см. в разделе <bpt id="p1">[</bpt>Общие сведения об использовании сценариев<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>.</target>       </trans-unit>
        <trans-unit id="123" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.String)">
          <source>The error message displayed to the client when the exception is thrown.</source>
          <target state="translated">Сообщение об ошибке, отображаемое клиенту при создании исключения.</target>       </trans-unit>
        <trans-unit id="124" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.String)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> class using a supplied error message.</source>
          <target state="translated">Выполняет инициализацию нового экземпляра класса <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> с заданным сообщением об ошибке.</target>       </trans-unit>
        <trans-unit id="125" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String)">
          <source>The following code example demonstrates the <ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph> constructor of the <ph id="ph2">&lt;xref:System.Web.HttpException&gt;</ph> class.</source>
          <target state="translated">В следующем примере кода показано <ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph> конструктор <ph id="ph2">&lt;xref:System.Web.HttpException&gt;</ph> класса.</target>       </trans-unit>
        <trans-unit id="126" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String)">
          <source>An <ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> is thrown if a user-entered value is 0.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> Возникает, если введенное пользователем значение равно 0.</target>       </trans-unit>
        <trans-unit id="127" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String)">
          <source>This example has a text box that accepts user input, which is a potential security threat.</source>
          <target state="translated">В этом примере имеется текстовое поле, принимающее вводимые пользователем данные, что является потенциальной угрозой безопасности.</target>       </trans-unit>
        <trans-unit id="128" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String)">
          <source>By default, ASP.NET Web pages validate that user input does not include script or HTML elements.</source>
          <target state="translated">По умолчанию данные, вводимые пользователем на веб-страницах ASP.NET, проверяются на наличие скриптов и HTML-элементов.</target>       </trans-unit>
        <trans-unit id="129" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String)">
          <source>For more information, see <bpt id="p1">[</bpt>Script Exploits Overview<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>.</source>
          <target state="translated">Дополнительные сведения см. в разделе <bpt id="p1">[</bpt>Общие сведения об использовании сценариев<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>.</target>       </trans-unit>
        <trans-unit id="130" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String)">
          <source>The HTTP response status code sent to the client corresponding to this error.</source>
          <target state="translated">Код состояния HTTP ответа, пересылаемый клиенту, соответствующему данной ошибке.</target>       </trans-unit>
        <trans-unit id="131" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String)">
          <source>The error message displayed to the client when the exception is thrown.</source>
          <target state="translated">Сообщение об ошибке, отображаемое клиенту при создании исключения.</target>       </trans-unit>
        <trans-unit id="132" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> class using an HTTP response status code and an error message.</source>
          <target state="translated">Выполняет инициализацию нового экземпляра класса <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph>, используя код состояния HTTP-ответа и сообщение об ошибке.</target>       </trans-unit>
        <trans-unit id="133" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph> that holds the serialized object data about the exception being thrown.</source>
          <target state="translated">Объект <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph>, хранящий сериализованные данные объекта, относящиеся к выдаваемому исключению.</target>       </trans-unit>
        <trans-unit id="134" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.StreamingContext" /&gt;</ph> that holds the contextual information about the source or destination.</source>
          <target state="translated">Контекст <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.StreamingContext" /&gt;</ph>, который содержит контекстные сведения об источнике или назначении.</target>       </trans-unit>
        <trans-unit id="135" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> class with serialized data.</source>
          <target state="translated">Инициализирует новый экземпляр класса <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> с сериализованными данными.</target>       </trans-unit>
        <trans-unit id="136" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The <ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph> constructor is called during deserialization to reconstitute the exception object that is transmitted over a stream.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph> Конструктор вызывается в процессе десериализации для воссоздания объекта исключения, переданного в потоке.</target>       </trans-unit>
        <trans-unit id="137" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>For more information, see <bpt id="p1">[</bpt>XML and SOAP Serialization<ept id="p1">](~/docs/standard/serialization/xml-and-soap-serialization.md)</ept>.</source>
          <target state="translated">Дополнительные сведения см. в разделе <bpt id="p1">[</bpt>сериализации XML и SOAP<ept id="p1">](~/docs/standard/serialization/xml-and-soap-serialization.md)</ept>.</target>       </trans-unit>
        <trans-unit id="138" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>The error message displayed to the client when the exception is thrown.</source>
          <target state="translated">Сообщение об ошибке, отображаемое клиенту при создании исключения.</target>       </trans-unit>
        <trans-unit id="139" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>The <ph id="ph1">&lt;see cref="P:System.Exception.InnerException" /&gt;</ph>, if any, that threw the current exception.</source>
          <target state="translated">Метод <ph id="ph1">&lt;see cref="P:System.Exception.InnerException" /&gt;</ph> (при наличии), вызвавший текущее исключение.</target>       </trans-unit>
        <trans-unit id="140" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> class using an error message and the <ph id="ph2">&lt;see cref="P:System.Exception.InnerException" /&gt;</ph> property.</source>
          <target state="translated">Выполняет инициализацию нового экземпляра класса <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph>, используя сообщение об ошибке и свойство <ph id="ph2">&lt;see cref="P:System.Exception.InnerException" /&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="141" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>When handling exceptions, it can be useful to capture a series of related exceptions with the outer exception being thrown in response to an inner exception.</source>
          <target state="translated">При обработке исключений, его можно использовать для захвата ряд исключений, связанных с внешней исключения в ответ на внутреннее исключение.</target>       </trans-unit>
        <trans-unit id="142" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>A reference to the inner exception that caused the outer exception is available from the <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property of the outer exception.</source>
          <target state="translated">Ссылка на внутреннее исключение, вызвавшее исключение внешнего доступна через <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> свойства внешнего исключения.</target>       </trans-unit>
        <trans-unit id="143" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>This mechanism preserves the error information that is carried by earlier exceptions, including the original exceptions, while allowing you to create more meaningful outer exceptions.</source>
          <target state="translated">Этот механизм сохраняет сведения об ошибке, переданные в более ранних исключениях, включая исходные исключения, предоставляя возможность создания более значимых внешних исключений.</target>       </trans-unit>
        <trans-unit id="144" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>For more information, see <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph>.</source>
          <target state="translated">Дополнительные сведения см. в разделе <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="145" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>The following code example demonstrates the <ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph> constructor of the <ph id="ph2">&lt;xref:System.Web.HttpException&gt;</ph> class.</source>
          <target state="translated">В следующем примере кода показано <ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph> конструктор <ph id="ph2">&lt;xref:System.Web.HttpException&gt;</ph> класса.</target>       </trans-unit>
        <trans-unit id="146" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>The <ph id="ph1">`CheckNumber`</ph> method accepts a user-entered value through a text box and checks whether it is an integer.</source>
          <target state="translated"><ph id="ph1">`CheckNumber`</ph> Метод введенное пользователем значение в текстовое поле и проверяет, является ли это целое число.</target>       </trans-unit>
        <trans-unit id="147" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>If the value is not an integer, an exception is thrown, and then in the catch block, a new <ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> object is created and thrown.</source>
          <target state="translated">Если значение не является целым числом, возникает исключение, а затем в блоке catch новый <ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> объект создается и исключение.</target>       </trans-unit>
        <trans-unit id="148" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>That exception is caught in the <ph id="ph1">`Button_Click`</ph> event handler and the error message is displayed on the browser.</source>
          <target state="translated">Что исключение перехватывается в <ph id="ph1">`Button_Click`</ph> обработчик событий и сообщение об ошибке отображается в браузере.</target>       </trans-unit>
        <trans-unit id="149" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>This example has a text box that accepts user input, which is a potential security threat.</source>
          <target state="translated">В этом примере имеется текстовое поле, принимающее вводимые пользователем данные, что является потенциальной угрозой безопасности.</target>       </trans-unit>
        <trans-unit id="150" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>By default, ASP.NET Web pages validate that user input does not include script or HTML elements.</source>
          <target state="translated">По умолчанию данные, вводимые пользователем на веб-страницах ASP.NET, проверяются на наличие скриптов и HTML-элементов.</target>       </trans-unit>
        <trans-unit id="151" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Exception)">
          <source>For more information, see <bpt id="p1">[</bpt>Script Exploits Overview<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>.</source>
          <target state="translated">Дополнительные сведения см. в разделе <bpt id="p1">[</bpt>Общие сведения об использовании сценариев<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>.</target>       </trans-unit>
        <trans-unit id="152" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.String,System.Int32)">
          <source>The error message displayed to the client when the exception is thrown.</source>
          <target state="translated">Сообщение об ошибке, отображаемое клиенту при создании исключения.</target>       </trans-unit>
        <trans-unit id="153" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.String,System.Int32)">
          <source>The exception code that defines the error.</source>
          <target state="translated">Код исключения с описанием ошибки.</target>       </trans-unit>
        <trans-unit id="154" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.String,System.Int32)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> class using an error message and an exception code.</source>
          <target state="translated">Выполняет инициализацию нового экземпляра класса <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph>, используя сообщение об ошибке и код исключения.</target>       </trans-unit>
        <trans-unit id="155" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Int32)">
          <source>The following code example demonstrates the <ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph> constructor of the <ph id="ph2">&lt;xref:System.Web.HttpException&gt;</ph> class.</source>
          <target state="translated">В следующем примере кода показано <ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph> конструктор <ph id="ph2">&lt;xref:System.Web.HttpException&gt;</ph> класса.</target>       </trans-unit>
        <trans-unit id="156" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Int32)">
          <source>An <ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> exception is thrown if a user-entered value is 0.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> Исключение вызывается, если введенное пользователем значение равно 0.</target>       </trans-unit>
        <trans-unit id="157" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Int32)">
          <source>This example has a text box that accepts user input, which is a potential security threat.</source>
          <target state="translated">В этом примере имеется текстовое поле, принимающее вводимые пользователем данные, что является потенциальной угрозой безопасности.</target>       </trans-unit>
        <trans-unit id="158" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Int32)">
          <source>By default, ASP.NET Web pages validate that user input does not include script or HTML elements.</source>
          <target state="translated">По умолчанию данные, вводимые пользователем на веб-страницах ASP.NET, проверяются на наличие скриптов и HTML-элементов.</target>       </trans-unit>
        <trans-unit id="159" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.String,System.Int32)">
          <source>For more information, see <bpt id="p1">[</bpt>Script Exploits Overview<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>.</source>
          <target state="translated">Дополнительные сведения см. в разделе <bpt id="p1">[</bpt>Общие сведения об использовании сценариев<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>.</target>       </trans-unit>
        <trans-unit id="160" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>The HTTP response status code displayed on the client.</source>
          <target state="translated">Код состояния HTTP-ответа, отображаемый клиентом.</target>       </trans-unit>
        <trans-unit id="161" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>The error message displayed to the client when the exception is thrown.</source>
          <target state="translated">Сообщение об ошибке, отображаемое клиенту при создании исключения.</target>       </trans-unit>
        <trans-unit id="162" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>The <ph id="ph1">&lt;see cref="P:System.Exception.InnerException" /&gt;</ph>, if any, that threw the current exception.</source>
          <target state="translated">Метод <ph id="ph1">&lt;see cref="P:System.Exception.InnerException" /&gt;</ph> (при наличии), вызвавший текущее исключение.</target>       </trans-unit>
        <trans-unit id="163" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> class using an HTTP response status code, an error message, and the <ph id="ph2">&lt;see cref="P:System.Exception.InnerException" /&gt;</ph> property.</source>
          <target state="translated">Выполняет инициализацию нового экземпляра класса <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph>, используя код состояния HTTP-ответа, сообщение об ошибке и свойство <ph id="ph2">&lt;see cref="P:System.Exception.InnerException" /&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="164" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>When handling exceptions, it can be useful to capture a series of related exceptions with the outer exception being thrown in response to an inner exception.</source>
          <target state="translated">При обработке исключений, его можно использовать для захвата ряд исключений, связанных с внешней исключения в ответ на внутреннее исключение.</target>       </trans-unit>
        <trans-unit id="165" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>A reference to the inner exception that caused the outer exception is available from the <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property of the outer exception.</source>
          <target state="translated">Ссылка на внутреннее исключение, вызвавшее исключение внешнего доступна через <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> свойства внешнего исключения.</target>       </trans-unit>
        <trans-unit id="166" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>This mechanism preserves the error information that is carried by earlier exceptions, including the original exceptions, while allowing you to create more meaningful outer exceptions.</source>
          <target state="translated">Этот механизм сохраняет сведения об ошибке, переданные в более ранних исключениях, включая исходные исключения, предоставляя возможность создания более значимых внешних исключений.</target>       </trans-unit>
        <trans-unit id="167" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>For more information, see <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph>.</source>
          <target state="translated">Дополнительные сведения см. в разделе <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="168" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>The following code example demonstrates the <ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph> constructor of the <ph id="ph2">&lt;xref:System.Web.HttpException&gt;</ph> class.</source>
          <target state="translated">В следующем примере кода показано <ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph> конструктор <ph id="ph2">&lt;xref:System.Web.HttpException&gt;</ph> класса.</target>       </trans-unit>
        <trans-unit id="169" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>The <ph id="ph1">`CheckNumber`</ph> method accepts a user-entered value and checks whether it is an integer.</source>
          <target state="translated"><ph id="ph1">`CheckNumber`</ph> Метод введенное пользователем значение и проверяет, является ли это целое число.</target>       </trans-unit>
        <trans-unit id="170" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>If the value is not an integer, an exception is thrown, and then a new <ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> object containing the HTTP response status code, the exception's message, and any inner exception is created.</source>
          <target state="translated">Если значение не является целым числом, создается исключение и создается новый <ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> создается объект, содержащий код состояния HTTP-ответа, сообщение об исключении и любое внутреннее исключение.</target>       </trans-unit>
        <trans-unit id="171" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>That exception is caught in the <ph id="ph1">`Button_Click`</ph> event handler and the error message, error code, and inner exception are displayed.</source>
          <target state="translated">Что исключение перехватывается в <ph id="ph1">`Button_Click`</ph> отображаются обработчик событий и сообщение об ошибке, код ошибки и внутреннее исключение.</target>       </trans-unit>
        <trans-unit id="172" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>This example has a text box that accepts user input, which is a potential security threat.</source>
          <target state="translated">В этом примере имеется текстовое поле, принимающее вводимые пользователем данные, что является потенциальной угрозой безопасности.</target>       </trans-unit>
        <trans-unit id="173" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>By default, ASP.NET Web pages validate that user input does not include script or HTML elements.</source>
          <target state="translated">По умолчанию данные, вводимые пользователем на веб-страницах ASP.NET, проверяются на наличие скриптов и HTML-элементов.</target>       </trans-unit>
        <trans-unit id="174" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)">
          <source>For more information, see <bpt id="p1">[</bpt>Script Exploits Overview<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>.</source>
          <target state="translated">Дополнительные сведения см. в разделе <bpt id="p1">[</bpt>Общие сведения об использовании сценариев<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>.</target>       </trans-unit>
        <trans-unit id="175" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Int32)">
          <source>The HTTP response status code displayed on the client.</source>
          <target state="translated">Код состояния HTTP-ответа, отображаемый клиентом.</target>       </trans-unit>
        <trans-unit id="176" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Int32)">
          <source>The error message displayed to the client when the exception is thrown.</source>
          <target state="translated">Сообщение об ошибке, отображаемое клиенту при создании исключения.</target>       </trans-unit>
        <trans-unit id="177" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Int32)">
          <source>The exception code that defines the error.</source>
          <target state="translated">Код исключения с описанием ошибки.</target>       </trans-unit>
        <trans-unit id="178" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Int32)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> class using an HTTP response status code, an error message, and an exception code.</source>
          <target state="translated">Выполняет инициализацию нового экземпляра класса <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph>, используя код состояния HTTP-ответа, сообщение об ошибке и код исключения.</target>       </trans-unit>
        <trans-unit id="179" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Int32)">
          <source>The following code example demonstrates the <ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph> constructor of the <ph id="ph2">&lt;xref:System.Web.HttpException&gt;</ph> class.</source>
          <target state="translated">В следующем примере кода показано <ph id="ph1">&lt;xref:System.Web.HttpException.%23ctor%2A&gt;</ph> конструктор <ph id="ph2">&lt;xref:System.Web.HttpException&gt;</ph> класса.</target>       </trans-unit>
        <trans-unit id="180" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Int32)">
          <source>The user name and email information are entered by the user in the provided text boxes.</source>
          <target state="translated">Имя и адрес электронной почты пользователя вводятся пользователем в предоставляемых текстовых полях.</target>       </trans-unit>
        <trans-unit id="181" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Int32)">
          <source>If any of the text boxes are left blank, an <ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> object is created and thrown.</source>
          <target state="translated">Если любой из поля оставлены пустыми, <ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> объект создается и исключение.</target>       </trans-unit>
        <trans-unit id="182" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Int32)">
          <source>The error code of the <ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> is obtained by the <ph id="ph2">&lt;xref:System.Web.HttpException.GetHttpCode%2A&gt;</ph> method and displayed on the Web page.</source>
          <target state="translated">Код ошибки <ph id="ph1">&lt;xref:System.Web.HttpException&gt;</ph> получается путем <ph id="ph2">&lt;xref:System.Web.HttpException.GetHttpCode%2A&gt;</ph> метод и отображается на веб-странице.</target>       </trans-unit>
        <trans-unit id="183" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Int32)">
          <source>This example has a text box that accepts user input, which is a potential security threat.</source>
          <target state="translated">В этом примере имеется текстовое поле, принимающее вводимые пользователем данные, что является потенциальной угрозой безопасности.</target>       </trans-unit>
        <trans-unit id="184" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Int32)">
          <source>By default, ASP.NET Web pages validate that user input does not include script or HTML elements.</source>
          <target state="translated">По умолчанию данные, вводимые пользователем на веб-страницах ASP.NET, проверяются на наличие скриптов и HTML-элементов.</target>       </trans-unit>
        <trans-unit id="185" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.#ctor(System.Int32,System.String,System.Int32)">
          <source>For more information, see <bpt id="p1">[</bpt>Script Exploits Overview<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>.</source>
          <target state="translated">Дополнительные сведения см. в разделе <bpt id="p1">[</bpt>Общие сведения об использовании сценариев<ept id="p1">](http://msdn.microsoft.com/library/772c7312-211a-4eb3-8d6e-eec0aa1dcc07)</ept>.</target>       </trans-unit>
        <trans-unit id="186" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.CreateFromLastError(System.String)">
          <source>The error message displayed to the client when the exception is thrown.</source>
          <target state="translated">Сообщение об ошибке, отображаемое клиенту при создании исключения.</target>       </trans-unit>
        <trans-unit id="187" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.CreateFromLastError(System.String)">
          <source>Creates a new <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> exception based on the error code that is returned from the Win32 API <ph id="ph2">&lt;see langword="GetLastError()" /&gt;</ph> method.</source>
          <target state="translated">Создает новое исключение <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> на основе кода ошибки, возвращенного методом <ph id="ph2">&lt;see langword="GetLastError()" /&gt;</ph> интерфейса Win32 API.</target>       </trans-unit>
        <trans-unit id="188" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.CreateFromLastError(System.String)">
          <source>An <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph> based on the error code that is returned from a call to the Win32 API <ph id="ph2">&lt;see langword="GetLastError()" /&gt;</ph> method.</source>
          <target state="translated">Исключение <ph id="ph1">&lt;see cref="T:System.Web.HttpException" /&gt;</ph>, которое создано с использованием кода ошибки, возвращенного при вызове метода <ph id="ph2">&lt;see langword="GetLastError()" /&gt;</ph> интерфейса Win32 API.</target>       </trans-unit>
        <trans-unit id="189" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.GetHtmlErrorMessage">
          <source>Gets the HTML error message to return to the client.</source>
          <target state="translated">Возвращает HTML-сообщение об ошибке для возврата клиенту.</target>       </trans-unit>
        <trans-unit id="190" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.GetHtmlErrorMessage">
          <source>The HTML error message.</source>
          <target state="translated">HTML-сообщение об ошибке.</target>       </trans-unit>
        <trans-unit id="191" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.GetHttpCode">
          <source>Gets the HTTP response status code to return to the client.</source>
          <target state="translated">Возвращает код состояния HTTP-ответа для передачи клиенту.</target>       </trans-unit>
        <trans-unit id="192" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.GetHttpCode">
          <source>A non-zero HTTP code representing the exception or the <ph id="ph1">&lt;see cref="P:System.Exception.InnerException" /&gt;</ph> code; otherwise, HTTP response status code 500.</source>
          <target state="translated">Ненулевой HTTP-код, представляющий исключение или код свойства <ph id="ph1">&lt;see cref="P:System.Exception.InnerException" /&gt;</ph>; в противном случае — код 500 состояния HTTP-ответа.</target>       </trans-unit>
        <trans-unit id="193" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.GetHttpCode">
          <source>If there is a non-zero HTTP code, it is returned.</source>
          <target state="translated">Если ненулевое значение HTTP-кодом, он возвращается.</target>       </trans-unit>
        <trans-unit id="194" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.GetHttpCode">
          <source>Otherwise, the <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> code is returned.</source>
          <target state="translated">В противном случае <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> возвращается код.</target>       </trans-unit>
        <trans-unit id="195" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.GetHttpCode">
          <source>If neither an <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> code nor a non-zero HTTP code is available, the HTTP response status code 500 is returned.</source>
          <target state="translated">Если ни одна из <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> кода и HTTP-кодом ненулевой недоступны, возвращается код состояния ответа HTTP 500.</target>       </trans-unit>
        <trans-unit id="196" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.GetHttpCode">
          <source>For more information on HTTP response status codes, see the Status Code Definitions of the Hypertext Transfer Protocol - HTTP/1.1 on the World <bpt id="p1">[</bpt>Wide Web Consortium (W3C) Web site<ept id="p1">](http://go.microsoft.com/fwlink/?linkid=37125)</ept>.</source>
          <target state="translated">Дополнительные сведения о кодах состояния ответа HTTP см. в разделе определения кодов состояния протокола передачи гипертекста - HTTP/1.1 по всему миру <bpt id="p1">[</bpt>широкий Web Consortium (W3C) веб-сайта<ept id="p1">](http://go.microsoft.com/fwlink/?linkid=37125)</ept>.</target>       </trans-unit>
        <trans-unit id="197" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph> that holds the serialized object data about the exception being thrown.</source>
          <target state="translated">Объект <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph>, хранящий сериализованные данные объекта, относящиеся к выдаваемому исключению.</target>       </trans-unit>
        <trans-unit id="198" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.StreamingContext" /&gt;</ph> that holds the contextual information about the source or destination.</source>
          <target state="translated">Контекст <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.StreamingContext" /&gt;</ph>, который содержит контекстные сведения об источнике или назначении.</target>       </trans-unit>
        <trans-unit id="199" translate="yes" xml:space="preserve" uid="M:System.Web.HttpException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>Gets information about the exception and adds it to the <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph> object.</source>
          <target state="translated">Возвращает сведения об исключении и добавляет их в объект <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="200" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The <ph id="ph1">&lt;xref:System.Web.HttpException.GetObjectData%2A&gt;</ph> method adds information about the exception to the <ph id="ph2">&lt;xref:System.Runtime.Serialization.SerializationInfo&gt;</ph> object that is targeted for serialization.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Web.HttpException.GetObjectData%2A&gt;</ph> Метод добавляет сведения об исключении для <ph id="ph2">&lt;xref:System.Runtime.Serialization.SerializationInfo&gt;</ph> , предназначенные для сериализации объекта.</target>       </trans-unit>
        <trans-unit id="201" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.HttpException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>During deserialization, the exception is reconstituted from the <ph id="ph1">&lt;xref:System.Runtime.Serialization.SerializationInfo&gt;</ph> that is transmitted over the stream.</source>
          <target state="translated">В процессе десериализации исключение воссоздается из <ph id="ph1">&lt;xref:System.Runtime.Serialization.SerializationInfo&gt;</ph> , переданного в потоке.</target>       </trans-unit>
        <trans-unit id="202" translate="yes" xml:space="preserve" uid="P:System.Web.HttpException.WebEventCode">
          <source>Gets the event codes that are associated with the HTTP exception.</source>
          <target state="translated">Получает коды событий, связанные с HTTP-исключением.</target>       </trans-unit>
        <trans-unit id="203" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Web.HttpException.WebEventCode">
          <source>An integer representing a Web event code.</source>
          <target state="translated">Целое число, представляющее код веб-события.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>